import Navbar from "@/components/Navbar";
import { Flex } from "@chakra-ui/react";
import Head from "next/head";

export const title = "Shubh's Website";

export default function Home() {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction={"column"} height={"full"}>
        <Navbar />
      </Flex>
    </>
  );
}
