import Navbar from "@/components/Navbar";
import Box from "@mui/material/Box";
import Head from "next/head";

export const title = "Shubh's Website";

export default function Home() {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          display: "flex",
          flexDirection: "column",
          height: "full",
        }}
      >
        <Navbar />
      </Box>
    </>
  );
}
